### ISSUE TITLE
Problem with WindowsPrintConnector.php

### ISSUE THREAD

**Issue by mountainclimbing** [mike42/escpos-php#715]
I have no luck with printing using the below example.

$connector = new WindowsPrintConnector("PrinterName");

The error am getting is with WindowsPrintConnector.php 
"Warning: copy(\\ComputerName\PrinterName): failed to open stream: Invalid argument in PartPath\vendor\mike42\escpos-php\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372"

And

"( ! )  Fatal error: Uncaught exception 'Exception' with message 'Failed to  copy file to printer' in  PartPath\vendor\mike42\escpos-php\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php  on line 291"

**Comment by mike42** [comment]
What type of printer do you have?

In #686 I pointed out that your HP DeskJet is not going to work with this library, have you changed printers since?

**Comment by mountainclimbing** [comment]
Hello @mike42,
I now have a thermal receipt printer and its among the listed tested printers.
Model: EPSON TM-T20II.

I have so far tried to rename the printer and share it but still no luck. I see the the path being correct as the error states, "Warning: copy(\\DESKTOP-50M0OBT\mbwepos): failed to open stream:....."

**Comment by mountainclimbing** [comment]
Hello @mike42,

the problem was with the servername. I fixed it and succeeded. 
Thank you!

**Comment by rajkumarpb** [comment]
> Hello @mike42,
> 
> the problem was with the servername. I fixed it and succeeded.
> Thank you!

Can you post your fix here? Getting same issue and still not able to fix it!

**Comment by paulowashington** [comment]
Nas propriedades da impressora, vá em compartilhamento e compartilhe a impresso. Só isso resolveu para mim.

**Comment by irfanjutt12** [comment]
Hi
I'm using Xprinter C260K and facing this error
copy(\\lenovo\jutttest): failed to open stream: No such file or directory
in WindowsPrintConnector.php line 378
at HandleExceptions->handleError(2, 'copy(\\\\lenovo\\jutttest): failed to open stream: No such file or directory', 'E:\\xampp\\htdocs\\ezpos\\vendor\\mike42\\escpos-php\\src\\Mike42\\Escpos\\PrintConnectors\\WindowsPrintConnector.php', 378, array('from' => 'C:\\Users\\ss\\AppData\\Local\\Temp\\esc606E.tmp', 'to' => '\\\\lenovo\\jutttest'))

at copy('C:\\Users\\ss\\AppData\\Local\\Temp\\esc606E.tmp', '\\\\lenovo\\jutttest')
in WindowsPrintConnector.php line 378

at WindowsPrintConnector->runCopy('C:\\Users\\ss\\AppData\\Local\\Temp\\esc606E.tmp', '\\\\lenovo\\jutttest')
in WindowsPrintConnector.php line 296

at WindowsPrintConnector->finalizeWin('@aOrderaReceipt!' . "\0" . '1/19/2018!French Deli & Gourmet Shop!' . "\0" . 'Order No.12345Phone: +1 (284) 494-2195!' . "\0" . 'Website: www.frenchdelibvi.com!' . "\0" . 'Cashier: jsimon!' . "\0" . '------------------------------------------a' . "\0" . 'EQty Name Unit Totala' . "\0" . 'E' . "\0" . '5 TEST ITEM 100 500-------------------------------------------aECUSTOMER COPYa' . "\0" . 'Change Return PolicyEkE12345aTHANK YOU!VAp0<x')
in WindowsPrintConnector.php line 176

Anyone help me to resolve this issue?
